version: 0.2

phases:

  pre_build:
    commands:
      - npm update -g npm
      - npm install -g yarn
      - yarn install

  build:
    commands:
      - NODE_ENV=production yarn build

  post_build:
    commands:
      - rm yarn.lock
      - rm -rf node_modules
      # - yarn install --production

artifacts:
  files:
    - '**/*'
